[project]
name = "ahc045"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "pulp>=3.1.1",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
]
