#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <iostream>
#include <limits>
#include <numeric>
#include <string>
#include <unordered_map>
#include <vector>

using namespace std;

static constexpr int N = 20;
static constexpr int CELLS = N * N; // 400
static constexpr int DIRS = 4;
static constexpr int WORDS = (CELLS + 63) / 64; // 7
static constexpr int MAXM = 3;

struct Mask {
    array<uint64_t, WORDS> w{};

    bool operator==(const Mask &other) const noexcept {
        return w == other.w;
    }
};

struct MaskHash {
    size_t operator()(const Mask &m) const noexcept {
        uint64_t h = 1469598103934665603ULL;
        for (uint64_t x : m.w) {
            h ^= x + 0x9e3779b97f4a7c15ULL + (h << 6) + (h >> 2);
        }
        return static_cast<size_t>(h);
    }
};

struct Pattern {
    int m = 1;
    array<char, MAXM> a0{'R', 'R', 'R'};
    array<uint8_t, MAXM> b0{0, 0, 0};
    array<char, MAXM> a1{'R', 'R', 'R'};
    array<uint8_t, MAXM> b1{0, 0, 0};
};

struct Candidate {
    int i = 0;
    int j = 0;
    int d = 0;
    int pat_idx = -1;
    int cost = 1;
    Mask mask{};
    vector<uint16_t> cells;
};

struct XorShift64 {
    uint64_t x;

    explicit XorShift64(uint64_t seed) : x(seed ? seed : 88172645463393265ULL) {}

    uint64_t next_u64() {
        x ^= x << 7;
        x ^= x >> 9;
        return x;
    }

    int next_int(int n) {
        return static_cast<int>(next_u64() % static_cast<uint64_t>(n));
    }

    double next_double() {
        return (next_u64() >> 11) * (1.0 / 9007199254740992.0);
    }
};

static inline void set_bit(Mask &m, int cell) {
    m.w[cell >> 6] |= (1ULL << (cell & 63));
}

static inline bool is_zero(const Mask &m) {
    for (uint64_t x : m.w) {
        if (x) return false;
    }
    return true;
}

static inline int popcount(const Mask &m) {
    int s = 0;
    for (uint64_t x : m.w)
        s += __builtin_popcountll(x);
    return s;
}

template <class F>
static inline void for_each_cell(const Mask &m, F &&f) {
    for (int wi = 0; wi < WORDS; wi++) {
        uint64_t x = m.w[wi];
        while (x) {
            int b = __builtin_ctzll(x);
            int cell = (wi << 6) + b;
            if (cell < CELLS) f(cell);
            x &= (x - 1);
        }
    }
}

static vector<Pattern> build_patterns() {
    vector<Pattern> pats;
    pats.reserve(128);

    // m=2 seeds (strong generic templates)
    // Bounce-R
    pats.push_back(Pattern{2, {'F', 'R', 'R'}, {0, 0, 0}, {'R', 'R', 'R'}, {1, 0, 0}});
    // Bounce-L
    pats.push_back(Pattern{2, {'F', 'L', 'R'}, {0, 0, 0}, {'L', 'L', 'R'}, {1, 0, 0}});
    // Snake RL
    pats.push_back(Pattern{2, {'F', 'F', 'R'}, {0, 1, 0}, {'R', 'L', 'R'}, {1, 0, 0}});
    // Snake LR
    pats.push_back(Pattern{2, {'F', 'F', 'R'}, {0, 1, 0}, {'L', 'R', 'R'}, {1, 0, 0}});

    // Auto-generated by m3_picker.cpp
    // top_k=64, boards=8
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {1, 2, 0}, {'R', 'L', 'R'}, {0, 1, 1}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {1, 2, 0}, {'R', 'L', 'L'}, {0, 0, 2}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {1, 2, 0}, {'R', 'R', 'L'}, {2, 1, 2}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {2, 0, 1}, {'L', 'L', 'R'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {2, 0, 1}, {'L', 'R', 'R'}, {0, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {2, 0, 1}, {'R', 'L', 'L'}, {0, 1, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {1, 2, 0}, {'L', 'L', 'R'}, {2, 1, 2}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {1, 2, 0}, {'L', 'R', 'R'}, {0, 0, 2}});
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {2, 0, 1}, {'R', 'L', 'R'}, {1, 1, 2}});
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {1, 2, 0}, {'L', 'R', 'L'}, {0, 1, 1}});
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {2, 0, 1}, {'L', 'R', 'L'}, {1, 1, 2}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {2, 0, 1}, {'R', 'R', 'L'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {2, 0, 1}, {'R', 'L', 'R'}, {0, 0, 2}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {2, 0, 1}, {'L', 'L', 'R'}, {0, 1, 1}});
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {2, 0, 1}, {'L', 'R', 'R'}, {2, 1, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {2, 0, 1}, {'R', 'R', 'L'}, {0, 1, 1}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {1, 2, 0}, {'L', 'R', 'L'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {2, 0, 1}, {'L', 'R', 'L'}, {0, 0, 2}});
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {1, 2, 0}, {'L', 'L', 'R'}, {0, 1, 0}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {1, 2, 0}, {'L', 'R', 'R'}, {1, 1, 2}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {1, 2, 0}, {'R', 'L', 'R'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {1, 2, 0}, {'R', 'L', 'L'}, {1, 1, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {2, 0, 1}, {'R', 'L', 'L'}, {2, 1, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {1, 2, 0}, {'R', 'R', 'L'}, {0, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {1, 0, 2}, {'L', 'L', 'R'}, {2, 0, 0}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {0, 2, 1}, {'R', 'L', 'L'}, {2, 2, 0}});
    pats.push_back(Pattern{3, {'R', 'F', 'R'}, {0, 2, 1}, {'R', 'R', 'L'}, {1, 0, 1}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {2, 1, 0}, {'L', 'R', 'L'}, {1, 0, 0}});
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {0, 2, 1}, {'R', 'L', 'L'}, {1, 0, 1}});
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {1, 0, 2}, {'L', 'L', 'R'}, {1, 2, 1}});
    pats.push_back(Pattern{3, {'R', 'R', 'F'}, {0, 2, 1}, {'R', 'L', 'R'}, {2, 2, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {2, 1, 0}, {'L', 'R', 'L'}, {2, 2, 1}});
    pats.push_back(Pattern{3, {'R', 'R', 'F'}, {2, 1, 0}, {'L', 'R', 'R'}, {2, 2, 1}});
    pats.push_back(Pattern{3, {'F', 'R', 'R'}, {2, 1, 0}, {'R', 'R', 'L'}, {1, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'F', 'R'}, {1, 0, 2}, {'L', 'R', 'R'}, {1, 2, 1}});
    pats.push_back(Pattern{3, {'F', 'R', 'R'}, {1, 0, 2}, {'R', 'L', 'R'}, {2, 0, 0}});
    pats.push_back(Pattern{3, {'F', 'L', 'L'}, {1, 0, 2}, {'L', 'R', 'L'}, {2, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {0, 2, 1}, {'L', 'R', 'R'}, {2, 2, 0}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {1, 0, 2}, {'R', 'R', 'L'}, {2, 0, 0}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {2, 1, 0}, {'R', 'L', 'R'}, {1, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {0, 2, 1}, {'L', 'R', 'R'}, {1, 0, 1}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {2, 1, 0}, {'R', 'L', 'R'}, {2, 2, 1}});
    pats.push_back(Pattern{3, {'L', 'F', 'L'}, {0, 2, 1}, {'L', 'L', 'R'}, {1, 0, 1}});
    pats.push_back(Pattern{3, {'F', 'L', 'L'}, {2, 1, 0}, {'L', 'L', 'R'}, {1, 0, 0}});
    pats.push_back(Pattern{3, {'L', 'L', 'F'}, {0, 2, 1}, {'L', 'R', 'L'}, {2, 2, 0}});
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {1, 0, 2}, {'R', 'R', 'L'}, {1, 2, 1}});
    pats.push_back(Pattern{3, {'L', 'F', 'L'}, {1, 0, 2}, {'R', 'L', 'L'}, {1, 2, 1}});
    pats.push_back(Pattern{3, {'L', 'L', 'F'}, {2, 1, 0}, {'R', 'L', 'L'}, {2, 2, 1}});
    pats.push_back(Pattern{3, {'F', 'F', 'L'}, {2, 1, 0}, {'L', 'R', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'F', 'F', 'L'}, {0, 2, 1}, {'R', 'L', 'R'}, {2, 1, 1}});
    pats.push_back(Pattern{3, {'F', 'L', 'L'}, {2, 2, 0}, {'L', 'R', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'L', 'L', 'F'}, {2, 2, 1}, {'R', 'R', 'L'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'L', 'F'}, {2, 2, 1}, {'L', 'R', 'L'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'L', 'L'}, {2, 2, 0}, {'L', 'L', 'L'}, {0, 2, 1}});
    pats.push_back(Pattern{3, {'F', 'F', 'L'}, {1, 2, 1}, {'L', 'L', 'R'}, {2, 1, 1}});
    pats.push_back(Pattern{3, {'L', 'F', 'F'}, {2, 2, 0}, {'R', 'L', 'L'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'L', 'F', 'L'}, {2, 2, 1}, {'R', 'L', 'R'}, {2, 1, 1}});
    pats.push_back(Pattern{3, {'L', 'F', 'F'}, {2, 2, 0}, {'R', 'R', 'L'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'L', 'F'}, {0, 2, 1}, {'R', 'R', 'L'}, {1, 2, 2}});
    pats.push_back(Pattern{3, {'L', 'F', 'L'}, {2, 2, 1}, {'L', 'L', 'L'}, {2, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'L', 'F'}, {1, 0, 1}, {'L', 'R', 'R'}, {0, 2, 1}});
    pats.push_back(Pattern{3, {'L', 'L', 'F'}, {1, 2, 1}, {'L', 'L', 'L'}, {1, 0, 2}});
    pats.push_back(Pattern{3, {'L', 'F', 'F'}, {1, 0, 0}, {'R', 'L', 'R'}, {1, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'R', 'F'}, {0, 2, 1}, {'R', 'L', 'R'}, {1, 2, 2}});

    return pats;
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    int Nin, AK, AM, AW;
    if (!(cin >> Nin >> AK >> AM >> AW)) return 0;

    vector<string> v(N), h(N - 1);
    for (int i = 0; i < N; i++)
        cin >> v[i];
    for (int i = 0; i < N - 1; i++)
        cin >> h[i];

    static const int di[4] = {-1, 0, 1, 0};
    static const int dj[4] = {0, 1, 0, -1};
    static const char DIR_CH[4] = {'U', 'R', 'D', 'L'};

    bool blocked[CELLS][DIRS];
    int forward_cell[CELLS][DIRS];
    for (int i = 0; i < N; i++) {
        for (int j = 0; j < N; j++) {
            int cell = i * N + j;
            for (int d = 0; d < DIRS; d++) {
                bool w = false;
                if (d == 0) {
                    w = (i == 0) || (h[i - 1][j] == '1');
                } else if (d == 1) {
                    w = (j == N - 1) || (v[i][j] == '1');
                } else if (d == 2) {
                    w = (i == N - 1) || (h[i][j] == '1');
                } else {
                    w = (j == 0) || (v[i][j - 1] == '1');
                }
                blocked[cell][d] = w;
                if (w) {
                    forward_cell[cell][d] = cell;
                } else {
                    int ni = i + di[d];
                    int nj = j + dj[d];
                    forward_cell[cell][d] = ni * N + nj;
                }
            }
        }
    }

    vector<Pattern> patterns = build_patterns();

    vector<Candidate> cands;
    cands.reserve(40000);
    unordered_map<Mask, int, MaskHash> uniq;
    uniq.reserve(1 << 16);

    auto add_candidate = [&](Candidate &&cand) {
        if (is_zero(cand.mask)) return;
        int cov = popcount(cand.mask);
        if (cov <= cand.cost) return;

        auto it = uniq.find(cand.mask);
        if (it == uniq.end()) {
            int id = (int)cands.size();
            uniq.emplace(cand.mask, id);
            cands.push_back(std::move(cand));
            return;
        }

        int id = it->second;
        if (cand.cost < cands[id].cost) {
            cands[id] = std::move(cand);
        }
    };

    auto generate_for_pattern = [&](int pat_idx) {
        const Pattern &p = patterns[pat_idx];
        int m = p.m;
        int S = CELLS * DIRS * m;

        vector<int> nxt(S);
        for (int node = 0; node < S; node++) {
            int s = node % m;
            int t = node / m;
            int d = t % DIRS;
            int cell = t / DIRS;

            bool w = blocked[cell][d];
            char act = w ? p.a1[s] : p.a0[s];
            int ns = w ? p.b1[s] : p.b0[s];

            int nd = d;
            int ncell = cell;
            if (act == 'F') {
                ncell = forward_cell[cell][d];
            } else if (act == 'R') {
                nd = (d + 1) & 3;
            } else {
                nd = (d + 3) & 3;
            }

            nxt[node] = ((ncell * DIRS + nd) * m + ns);
        }

        vector<uint8_t> state(S, 0); // 0 unvisited, 1 visiting, 2 done
        vector<int> idx(S, -1);
        vector<int> comp(S, -1);
        vector<int> path;
        path.reserve(S);

        int cycle_count = 0;
        vector<vector<int>> cycles;
        cycles.reserve(S / 2 + 1);
        for (int st = 0; st < S; st++) {
            if (state[st] != 0) continue;

            path.clear();
            int u = st;
            while (state[u] == 0) {
                state[u] = 1;
                idx[u] = (int)path.size();
                path.push_back(u);
                u = nxt[u];
            }

            if (state[u] == 1) {
                int from = idx[u];
                int cid = cycle_count++;
                cycles.emplace_back();
                cycles.back().reserve((int)path.size() - from);
                for (int t = from; t < (int)path.size(); t++) {
                    int vtx = path[t];
                    comp[vtx] = cid;
                    state[vtx] = 2;
                    cycles.back().push_back(vtx);
                }
            }

            for (int t = (int)path.size() - 1; t >= 0; t--) {
                int vtx = path[t];
                if (state[vtx] == 2) continue;
                comp[vtx] = comp[nxt[vtx]];
                state[vtx] = 2;
            }

            for (int vtx : path)
                idx[vtx] = -1;
        }

        vector<Mask> cycle_masks(cycle_count);
        for (int cid = 0; cid < cycle_count; cid++) {
            for (int node : cycles[cid]) {
                int cell = node / (DIRS * m);
                set_bit(cycle_masks[cid], cell);
            }
        }

        vector<vector<uint16_t>> cycle_cells(cycle_count);
        for (int cid = 0; cid < cycle_count; cid++) {
            for_each_cell(cycle_masks[cid], [&](int cell) {
                cycle_cells[cid].push_back((uint16_t)cell);
            });
        }

        for (int cell = 0; cell < CELLS; cell++) {
            int i = cell / N;
            int j = cell % N;
            for (int d = 0; d < DIRS; d++) {
                int st_node = ((cell * DIRS + d) * m + 0);
                int cid = comp[st_node];

                Candidate cand;
                cand.i = i;
                cand.j = j;
                cand.d = d;
                cand.pat_idx = pat_idx;
                cand.cost = m;
                cand.mask = cycle_masks[cid];
                cand.cells = cycle_cells[cid];
                add_candidate(std::move(cand));
            }
        }
    };

    for (int pat_idx = 0; pat_idx < (int)patterns.size(); pat_idx++) {
        generate_for_pattern(pat_idx);
    }

    const int C = (int)cands.size();
    vector<char> lp_selected(C, 0);
    int lp_cost = 0;
    int lp_uncovered = CELLS;

    // LP relaxation + randomized rounding for weighted set cover.
    if (C > 0) {
        uint64_t lp_seed = (uint64_t)chrono::high_resolution_clock::now().time_since_epoch().count();
        lp_seed ^= (uint64_t)Nin * 1000003ULL + (uint64_t)AK * 10007ULL + (uint64_t)AM * 257ULL + (uint64_t)AW;
        XorShift64 rng_lp(lp_seed ^ 0x9e3779b97f4a7c15ULL);

        vector<double> x(C, 0.0);
        vector<double> load(CELLS, 0.0);
        vector<double> w(CELLS, 0.0);
        const double mu = 0.25;

        auto lp_deadline = chrono::steady_clock::now() + chrono::milliseconds(180);
        for (int it = 0; it < 4000; it++) {
            if (chrono::steady_clock::now() >= lp_deadline) break;

            for (int c = 0; c < CELLS; c++) {
                double z = (1.0 - load[c]) / mu;
                if (z > 20.0) z = 20.0;
                if (z < -20.0) z = -20.0;
                w[c] = exp(z);
            }

            int best = -1;
            double best_ratio = 1.0001;
            double best_score = 0.0;
            for (int id = 0; id < C; id++) {
                if (x[id] >= 0.999999) continue;
                double score = 0.0;
                for (uint16_t cell : cands[id].cells)
                    score += w[cell];
                double ratio = score / (double)cands[id].cost;
                if (ratio > best_ratio) {
                    best_ratio = ratio;
                    best_score = score;
                    best = id;
                }
            }

            if (best < 0) break;
            double delta = mu * log(best_score / (double)cands[best].cost);
            if (delta < 1e-4) delta = 1e-4;
            double room = 1.0 - x[best];
            if (delta > room) delta = room;
            if (delta <= 1e-12) break;

            x[best] += delta;
            for (uint16_t cell : cands[best].cells)
                load[cell] += delta;
        }

        vector<int> order(C);
        iota(order.begin(), order.end(), 0);
        sort(order.begin(), order.end(), [&](int a, int b) {
            if (x[a] != x[b]) return x[a] > x[b];
            if (cands[a].cost != cands[b].cost) return cands[a].cost < cands[b].cost;
            return cands[a].cells.size() > cands[b].cells.size();
        });

        auto round_deadline = chrono::steady_clock::now() + chrono::milliseconds(220);
        int best_unc = CELLS + 1;
        int best_cost_lp = numeric_limits<int>::max();
        vector<char> best_sel_lp(C, 0);

        auto evaluate_pick = [&](const vector<char>& pick) {
            vector<int> cc(CELLS, 0);
            int unc = CELLS;
            int cost = 0;
            for (int id = 0; id < C; id++) {
                if (!pick[id]) continue;
                cost += cands[id].cost;
                for (uint16_t cell : cands[id].cells) {
                    if (cc[cell] == 0) unc--;
                    cc[cell]++;
                }
            }
            return pair<int, int>(unc, cost);
        };

        const int trials = 36;
        for (int tr = 0; tr < trials; tr++) {
            if (chrono::steady_clock::now() >= round_deadline) break;

            vector<char> pick(C, 0);
            vector<int> cc(CELLS, 0);
            int unc = CELLS;
            int cost = 0;

            auto add_id = [&](int id) {
                if (pick[id]) return;
                pick[id] = 1;
                cost += cands[id].cost;
                for (uint16_t cell : cands[id].cells) {
                    if (cc[cell] == 0) unc--;
                    cc[cell]++;
                }
            };

            for (int id : order) {
                if (x[id] < 0.93) break;
                add_id(id);
            }

            double alpha = 1.10 + 0.90 * (double)tr / (double)max(1, trials - 1);
            for (int id : order) {
                if (pick[id]) continue;
                double p = x[id] * alpha;
                if (p > 1.0) p = 1.0;
                if (p > 1e-9 && rng_lp.next_double() < p) add_id(id);
            }

            while (unc > 0) {
                int best = -1;
                int best_gain = 0;
                double best_metric = 1e100;
                for (int id = 0; id < C; id++) {
                    if (pick[id]) continue;
                    int gain = 0;
                    for (uint16_t cell : cands[id].cells) {
                        if (cc[cell] == 0) gain++;
                    }
                    if (gain == 0) continue;
                    double metric = (double)cands[id].cost / (double)gain;
                    metric /= (1.0 + 0.25 * x[id]);
                    if (metric < best_metric || (metric == best_metric && gain > best_gain)) {
                        best_metric = metric;
                        best_gain = gain;
                        best = id;
                    }
                }
                if (best < 0) break;
                add_id(best);
                if (chrono::steady_clock::now() >= round_deadline) break;
            }

            if (unc == 0) {
                bool changed = true;
                while (changed) {
                    changed = false;
                    for (int id = 0; id < C; id++) {
                        if (!pick[id]) continue;
                        bool removable = true;
                        for (uint16_t cell : cands[id].cells) {
                            if (cc[cell] <= 1) {
                                removable = false;
                                break;
                            }
                        }
                        if (!removable) continue;
                        pick[id] = 0;
                        cost -= cands[id].cost;
                        for (uint16_t cell : cands[id].cells)
                            cc[cell]--;
                        changed = true;
                    }
                }
            }

            if (unc < best_unc || (unc == best_unc && cost < best_cost_lp)) {
                best_unc = unc;
                best_cost_lp = cost;
                best_sel_lp = pick;
            }
        }

        if (best_unc <= CELLS) {
            lp_selected = std::move(best_sel_lp);
            lp_cost = best_cost_lp;
            lp_uncovered = best_unc;
        } else {
            auto [unc, cost] = evaluate_pick(lp_selected);
            lp_uncovered = unc;
            lp_cost = cost;
        }
    }

    vector<char> selected(C, 0);
    vector<int> cover_cnt(CELLS, 0);
    int uncovered = CELLS;
    int cost_sum = 0;

    auto objective = [&]() -> int {
        return cost_sum + uncovered;
    };

    // Greedy initialization: add candidate if it strictly improves objective.
    while (true) {
        int best = -1;
        int best_delta = 0;
        int best_gain = 0;

        for (int id = 0; id < C; id++) {
            int gain = 0;
            for (uint16_t cell : cands[id].cells) {
                if (cover_cnt[cell] == 0) gain++;
            }
            int delta = cands[id].cost - gain;
            if (best == -1 || delta < best_delta || (delta == best_delta && gain > best_gain)) {
                best = id;
                best_delta = delta;
                best_gain = gain;
            }
        }

        if (best == -1 || best_delta >= 0) break;

        selected[best] = 1;
        cost_sum += cands[best].cost;
        for (uint16_t cell : cands[best].cells) {
            if (cover_cnt[cell] == 0) uncovered--;
            cover_cnt[cell]++;
        }
    }

    int best_obj = objective();
    vector<char> best_selected = selected;

    // Simulated annealing with toggle moves.
    if (C > 0) {
        const auto start_time = chrono::steady_clock::now();
        const double time_limit = 1.25;
        const double T0 = 2.5;
        const double T1 = 0.02;

        uint64_t seed = (uint64_t)chrono::high_resolution_clock::now().time_since_epoch().count();
        seed ^= (uint64_t)Nin * 1000003ULL + (uint64_t)AK * 10007ULL + (uint64_t)AM * 257ULL + (uint64_t)AW;
        XorShift64 rng(seed);

        double temp = T0;
        int iter = 0;

        while (true) {
            if ((iter & 255) == 0) {
                double elapsed = chrono::duration<double>(chrono::steady_clock::now() - start_time).count();
                if (elapsed >= time_limit) break;
                double p = elapsed / time_limit;
                temp = T0 * pow(T1 / T0, p);
            }
            iter++;

            int id = rng.next_int(C);
            int delta;
            if (selected[id]) {
                int lost = 0;
                for (uint16_t cell : cands[id].cells) {
                    if (cover_cnt[cell] == 1) lost++;
                }
                delta = -cands[id].cost + lost;
            } else {
                int gain = 0;
                for (uint16_t cell : cands[id].cells) {
                    if (cover_cnt[cell] == 0) gain++;
                }
                delta = cands[id].cost - gain;
            }

            bool accept = false;
            if (delta <= 0) {
                accept = true;
            } else {
                double prob = exp(-double(delta) / temp);
                if (rng.next_double() < prob) accept = true;
            }
            if (!accept) continue;

            if (selected[id]) {
                selected[id] = 0;
                cost_sum -= cands[id].cost;
                for (uint16_t cell : cands[id].cells) {
                    cover_cnt[cell]--;
                    if (cover_cnt[cell] == 0) uncovered++;
                }
            } else {
                selected[id] = 1;
                cost_sum += cands[id].cost;
                for (uint16_t cell : cands[id].cells) {
                    if (cover_cnt[cell] == 0) uncovered--;
                    cover_cnt[cell]++;
                }
            }

            int obj = objective();
            if (obj < best_obj) {
                best_obj = obj;
                best_selected = selected;
            }
        }
    }

    int best_cost_now = 0;
    int best_unc_now = CELLS;
    {
        vector<int> cc(CELLS, 0);
        for (int id = 0; id < C; id++) {
            if (!best_selected[id]) continue;
            best_cost_now += cands[id].cost;
            for (uint16_t cell : cands[id].cells) {
                if (cc[cell] == 0) best_unc_now--;
                cc[cell]++;
            }
        }
    }

    int lp_obj = lp_cost + lp_uncovered;
    int best_obj_now = best_cost_now + best_unc_now;
    if (lp_obj < best_obj_now ||
        (lp_obj == best_obj_now &&
         (lp_uncovered < best_unc_now || (lp_uncovered == best_unc_now && lp_cost < best_cost_now)))) {
        best_obj = lp_obj;
        best_selected = lp_selected;
    }

    // Restore best solution and perform deterministic local prune.
    selected = best_selected;
    fill(cover_cnt.begin(), cover_cnt.end(), 0);
    cost_sum = 0;
    for (int id = 0; id < C; id++) {
        if (!selected[id]) continue;
        cost_sum += cands[id].cost;
        for (uint16_t cell : cands[id].cells)
            cover_cnt[cell]++;
    }
    uncovered = 0;
    for (int c = 0; c < CELLS; c++) {
        if (cover_cnt[c] == 0) uncovered++;
    }

    bool improved = true;
    while (improved) {
        improved = false;
        for (int id = 0; id < C; id++) {
            if (!selected[id]) continue;

            int lost = 0;
            for (uint16_t cell : cands[id].cells) {
                if (cover_cnt[cell] == 1) lost++;
            }
            int delta = -cands[id].cost + lost;
            if (delta < 0) {
                selected[id] = 0;
                cost_sum -= cands[id].cost;
                for (uint16_t cell : cands[id].cells) {
                    cover_cnt[cell]--;
                }
                improved = true;
                break;
            }
        }
    }

    // Build output robots.
    struct RobotOut {
        int m;
        int i, j, d;
        array<char, MAXM> a0;
        array<uint8_t, MAXM> b0;
        array<char, MAXM> a1;
        array<uint8_t, MAXM> b1;
    };

    vector<RobotOut> robots;
    robots.reserve(CELLS);

    for (int id = 0; id < C; id++) {
        if (!selected[id]) continue;
        const Candidate &c = cands[id];
        const Pattern &p = patterns[c.pat_idx];

        RobotOut rb;
        rb.m = p.m;
        rb.i = c.i;
        rb.j = c.j;
        rb.d = c.d;
        rb.a0 = p.a0;
        rb.b0 = p.b0;
        rb.a1 = p.a1;
        rb.b1 = p.b1;
        robots.push_back(rb);
    }

    for (int cell = 0; cell < CELLS; cell++) {
        if (cover_cnt[cell] > 0) continue;
        RobotOut rb;
        rb.m = 1;
        rb.i = cell / N;
        rb.j = cell % N;
        rb.d = 0;
        rb.a0 = {'R', 'R', 'R'};
        rb.b0 = {0, 0, 0};
        rb.a1 = {'R', 'R', 'R'};
        rb.b1 = {0, 0, 0};
        robots.push_back(rb);
    }

    // Output
    cout << robots.size() << '\n';
    for (const auto &rb : robots) {
        cout << rb.m << ' ' << rb.i << ' ' << rb.j << ' ' << DIR_CH[rb.d] << '\n';
        for (int s = 0; s < rb.m; s++) {
            cout << rb.a0[s] << ' ' << (int)rb.b0[s] << ' ' << rb.a1[s] << ' ' << (int)rb.b1[s] << '\n';
        }
    }

    // A problem: no additional walls.
    for (int i = 0; i < N; i++)
        cout << string(N - 1, '0') << '\n';
    for (int i = 0; i < N - 1; i++)
        cout << string(N, '0') << '\n';

    return 0;
}
