#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <iostream>
#include <limits>
#include <string>
#include <unordered_map>
#include <vector>

using namespace std;

static constexpr int N = 20;
static constexpr int CELLS = N * N; // 400
static constexpr int DIRS = 4;
static constexpr int WORDS = (CELLS + 63) / 64; // 7
static constexpr int MAXM = 3;

struct Mask {
    array<uint64_t, WORDS> w{};

    bool operator==(const Mask &other) const noexcept {
        return w == other.w;
    }
};

struct MaskHash {
    size_t operator()(const Mask &m) const noexcept {
        uint64_t h = 1469598103934665603ULL;
        for (uint64_t x : m.w) {
            h ^= x + 0x9e3779b97f4a7c15ULL + (h << 6) + (h >> 2);
        }
        return static_cast<size_t>(h);
    }
};

struct Pattern {
    int m = 1;
    array<char, MAXM> a0{'R', 'R', 'R'};
    array<uint8_t, MAXM> b0{0, 0, 0};
    array<char, MAXM> a1{'R', 'R', 'R'};
    array<uint8_t, MAXM> b1{0, 0, 0};
};

struct Candidate {
    int i = 0;
    int j = 0;
    int d = 0;
    int pat_idx = -1;
    int cost = 1;
    Mask mask{};
    vector<uint16_t> cells;
};

struct XorShift64 {
    uint64_t x;

    explicit XorShift64(uint64_t seed) : x(seed ? seed : 88172645463393265ULL) {}

    uint64_t next_u64() {
        x ^= x << 7;
        x ^= x >> 9;
        return x;
    }

    int next_int(int n) {
        return static_cast<int>(next_u64() % static_cast<uint64_t>(n));
    }

    double next_double() {
        return (next_u64() >> 11) * (1.0 / 9007199254740992.0);
    }
};

static inline void set_bit(Mask &m, int cell) {
    m.w[cell >> 6] |= (1ULL << (cell & 63));
}

static inline void clear_bit(Mask &m, int cell) {
    m.w[cell >> 6] &= ~(1ULL << (cell & 63));
}

static inline bool test_bit(const Mask &m, int cell) {
    return ((m.w[cell >> 6] >> (cell & 63)) & 1ULL) != 0ULL;
}

static inline bool is_zero(const Mask &m) {
    for (uint64_t x : m.w) {
        if (x) return false;
    }
    return true;
}

static inline int popcount(const Mask &m) {
    int s = 0;
    for (uint64_t x : m.w)
        s += __builtin_popcountll(x);
    return s;
}

static inline int popcount_and(const Mask &a, const Mask &b) {
    int s = 0;
    for (int wi = 0; wi < WORDS; wi++) {
        s += __builtin_popcountll(a.w[wi] & b.w[wi]);
    }
    return s;
}

template <class F>
static inline void for_each_cell(const Mask &m, F &&f) {
    for (int wi = 0; wi < WORDS; wi++) {
        uint64_t x = m.w[wi];
        while (x) {
            int b = __builtin_ctzll(x);
            int cell = (wi << 6) + b;
            if (cell < CELLS) f(cell);
            x &= (x - 1);
        }
    }
}

static vector<Pattern> build_patterns() {
    vector<Pattern> pats;
    pats.reserve(128);

    // m=2 seeds (strong generic templates)
    // Bounce-R
    pats.push_back(Pattern{2, {'F', 'R', 'R'}, {0, 0, 0}, {'R', 'R', 'R'}, {1, 0, 0}});
    // Bounce-L
    pats.push_back(Pattern{2, {'F', 'L', 'R'}, {0, 0, 0}, {'L', 'L', 'R'}, {1, 0, 0}});
    // Snake RL
    pats.push_back(Pattern{2, {'F', 'F', 'R'}, {0, 1, 0}, {'R', 'L', 'R'}, {1, 0, 0}});
    // Snake LR
    pats.push_back(Pattern{2, {'F', 'F', 'R'}, {0, 1, 0}, {'L', 'R', 'R'}, {1, 0, 0}});

    // Auto-generated by m3_picker.cpp
    // top_k=200, boards=15
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {1, 2, 0}, {'L', 'R', 'L'}, {0, 1, 1}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {2, 0, 1}, {'L', 'R', 'R'}, {0, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {1, 2, 0}, {'L', 'R', 'R'}, {0, 0, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {2, 0, 1}, {'L', 'R', 'L'}, {1, 1, 2}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {1, 2, 0}, {'R', 'R', 'L'}, {2, 1, 2}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {1, 2, 0}, {'L', 'L', 'R'}, {2, 1, 2}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {2, 0, 1}, {'L', 'L', 'R'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {2, 0, 1}, {'R', 'L', 'L'}, {0, 1, 0}});
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {2, 0, 1}, {'R', 'L', 'R'}, {1, 1, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {1, 2, 0}, {'R', 'L', 'R'}, {0, 1, 1}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {2, 0, 1}, {'R', 'R', 'L'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {1, 2, 0}, {'R', 'L', 'L'}, {0, 0, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {1, 2, 0}, {'L', 'R', 'L'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {2, 0, 1}, {'L', 'R', 'R'}, {2, 1, 2}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {1, 2, 0}, {'R', 'L', 'L'}, {1, 1, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {2, 0, 1}, {'R', 'L', 'L'}, {2, 1, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {1, 2, 0}, {'R', 'R', 'L'}, {0, 1, 0}});
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {1, 2, 0}, {'L', 'L', 'R'}, {0, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {2, 0, 1}, {'R', 'R', 'L'}, {0, 1, 1}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {2, 0, 1}, {'L', 'R', 'L'}, {0, 0, 2}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {2, 0, 1}, {'L', 'L', 'R'}, {0, 1, 1}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {1, 2, 0}, {'R', 'L', 'R'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {2, 0, 1}, {'R', 'L', 'R'}, {0, 0, 2}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {1, 2, 0}, {'L', 'R', 'R'}, {1, 1, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {2, 1, 0}, {'R', 'L', 'R'}, {1, 0, 0}});
    pats.push_back(Pattern{3, {'F', 'L', 'L'}, {2, 1, 0}, {'L', 'L', 'R'}, {1, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {0, 2, 1}, {'L', 'R', 'R'}, {1, 0, 1}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {2, 1, 0}, {'R', 'L', 'R'}, {2, 2, 1}});
    pats.push_back(Pattern{3, {'L', 'F', 'L'}, {0, 2, 1}, {'L', 'L', 'R'}, {1, 0, 1}});
    pats.push_back(Pattern{3, {'F', 'L', 'L'}, {1, 0, 2}, {'L', 'R', 'L'}, {2, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {0, 2, 1}, {'L', 'R', 'R'}, {2, 2, 0}});
    pats.push_back(Pattern{3, {'L', 'L', 'F'}, {0, 2, 1}, {'L', 'R', 'L'}, {2, 2, 0}});
    pats.push_back(Pattern{3, {'L', 'F', 'L'}, {1, 0, 2}, {'R', 'L', 'L'}, {1, 2, 1}});
    pats.push_back(Pattern{3, {'L', 'L', 'F'}, {2, 1, 0}, {'R', 'L', 'L'}, {2, 2, 1}});
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {1, 0, 2}, {'R', 'R', 'L'}, {1, 2, 1}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {1, 0, 2}, {'R', 'R', 'L'}, {2, 0, 0}});
    pats.push_back(Pattern{3, {'F', 'L', 'F'}, {0, 2, 1}, {'L', 'R', 'L'}, {1, 2, 2}});
    pats.push_back(Pattern{3, {'L', 'F', 'L'}, {0, 2, 1}, {'R', 'L', 'R'}, {2, 1, 1}});
    pats.push_back(Pattern{3, {'F', 'L', 'L'}, {2, 0, 0}, {'L', 'R', 'R'}, {0, 2, 0}});
    pats.push_back(Pattern{3, {'L', 'F', 'F'}, {2, 2, 0}, {'R', 'L', 'L'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {2, 2, 0}, {'L', 'L', 'R'}, {0, 2, 0}});
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {1, 2, 1}, {'L', 'L', 'R'}, {0, 1, 1}});
    pats.push_back(Pattern{3, {'F', 'L', 'L'}, {1, 0, 1}, {'L', 'L', 'L'}, {0, 2, 1}});
    pats.push_back(Pattern{3, {'F', 'L', 'F'}, {2, 2, 1}, {'R', 'R', 'L'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {1, 0, 1}, {'L', 'R', 'L'}, {0, 2, 0}});
    pats.push_back(Pattern{3, {'L', 'F', 'F'}, {2, 2, 0}, {'R', 'R', 'L'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {2, 2, 0}, {'R', 'L', 'L'}, {2, 0, 2}});
    pats.push_back(Pattern{3, {'F', 'L', 'F'}, {1, 0, 1}, {'L', 'R', 'R'}, {0, 2, 1}});
    pats.push_back(Pattern{3, {'L', 'F', 'L'}, {1, 0, 0}, {'L', 'L', 'L'}, {2, 1, 0}});
    pats.push_back(Pattern{3, {'L', 'L', 'F'}, {2, 0, 0}, {'R', 'R', 'L'}, {2, 0, 2}});
    pats.push_back(Pattern{3, {'F', 'F', 'L'}, {2, 2, 0}, {'L', 'L', 'R'}, {0, 2, 0}});
    pats.push_back(Pattern{3, {'F', 'F', 'L'}, {2, 2, 0}, {'L', 'R', 'R'}, {0, 2, 1}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {2, 2, 1}, {'L', 'R', 'L'}, {1, 2, 2}});
    pats.push_back(Pattern{2, {'F', 'L', 'R'}, {1, 0, 0}, {'L', 'R', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'F', 'F', 'L'}, {1, 2, 1}, {'R', 'L', 'R'}, {0, 1, 1}});
    pats.push_back(Pattern{3, {'L', 'F', 'F'}, {1, 0, 0}, {'R', 'L', 'R'}, {1, 1, 0}});
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {1, 0, 0}, {'R', 'L', 'L'}, {1, 1, 0}});
    pats.push_back(Pattern{3, {'L', 'L', 'F'}, {2, 0, 0}, {'L', 'L', 'L'}, {1, 0, 2}});
    pats.push_back(Pattern{2, {'L', 'F', 'R'}, {1, 0, 0}, {'R', 'L', 'R'}, {1, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'R', 'R'}, {1, 0, 2}, {'R', 'L', 'R'}, {2, 0, 0}});
    pats.push_back(Pattern{3, {'F', 'R', 'R'}, {2, 1, 0}, {'R', 'R', 'L'}, {1, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'R', 'F'}, {2, 1, 0}, {'L', 'R', 'R'}, {2, 2, 1}});
    pats.push_back(Pattern{3, {'R', 'F', 'R'}, {0, 2, 1}, {'R', 'R', 'L'}, {1, 0, 1}});
    pats.push_back(Pattern{3, {'R', 'F', 'R'}, {1, 0, 2}, {'L', 'R', 'R'}, {1, 2, 1}});
    pats.push_back(Pattern{3, {'R', 'R', 'F'}, {0, 2, 1}, {'R', 'L', 'R'}, {2, 2, 0}});
    pats.push_back(Pattern{3, {'F', 'F', 'R'}, {2, 2, 1}, {'L', 'R', 'L'}, {2, 1, 1}});
    pats.push_back(Pattern{3, {'R', 'F', 'R'}, {1, 2, 1}, {'L', 'R', 'L'}, {0, 1, 1}});
    pats.push_back(Pattern{3, {'F', 'F', 'R'}, {2, 2, 1}, {'R', 'R', 'L'}, {1, 0, 1}});
    pats.push_back(Pattern{3, {'R', 'F', 'F'}, {2, 2, 0}, {'L', 'R', 'R'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'F'}, {2, 2, 0}, {'L', 'L', 'R'}, {2, 0, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'F'}, {2, 2, 1}, {'R', 'L', 'R'}, {1, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'F'}, {0, 2, 1}, {'L', 'L', 'R'}, {1, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'R', 'F'}, {0, 2, 1}, {'L', 'L', 'R'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'R'}, {2, 2, 0}, {'R', 'L', 'L'}, {0, 2, 0}});
    pats.push_back(Pattern{3, {'F', 'R', 'R'}, {2, 2, 0}, {'R', 'R', 'R'}, {0, 2, 1}});
    pats.push_back(Pattern{3, {'R', 'F', 'R'}, {2, 2, 1}, {'R', 'R', 'R'}, {2, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'F', 'R'}, {2, 2, 0}, {'R', 'L', 'L'}, {0, 2, 1}});
    pats.push_back(Pattern{2, {'R', 'F', 'R'}, {1, 0, 0}, {'L', 'R', 'R'}, {1, 1, 0}});
    pats.push_back(Pattern{3, {'R', 'R', 'F'}, {1, 2, 1}, {'R', 'R', 'R'}, {1, 0, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'F'}, {1, 0, 0}, {'L', 'R', 'L'}, {1, 1, 0}});
    pats.push_back(Pattern{2, {'F', 'R', 'R'}, {1, 0, 0}, {'R', 'L', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'F', 'R', 'F'}, {1, 0, 1}, {'R', 'L', 'L'}, {0, 2, 1}});
    pats.push_back(Pattern{3, {'L', 'F', 'L'}, {0, 2, 1}, {'L', 'R', 'L'}, {1, 1, 0}});
    pats.push_back(Pattern{3, {'L', 'L', 'F'}, {0, 2, 1}, {'L', 'L', 'R'}, {2, 0, 2}});
    pats.push_back(Pattern{3, {'R', 'R', 'F'}, {2, 1, 0}, {'R', 'R', 'L'}, {1, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'R'}, {2, 1, 0}, {'L', 'R', 'R'}, {0, 0, 1}});
    pats.push_back(Pattern{3, {'R', 'F', 'R'}, {1, 0, 2}, {'R', 'L', 'R'}, {2, 1, 1}});
    pats.push_back(Pattern{3, {'F', 'L', 'L'}, {1, 0, 2}, {'R', 'L', 'L'}, {0, 2, 0}});
    pats.push_back(Pattern{3, {'F', 'L', 'F'}, {1, 2, 0}, {'R', 'L', 'R'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'F', 'L'}, {1, 2, 0}, {'R', 'R', 'L'}, {0, 1, 0}});
    pats.push_back(Pattern{3, {'L', 'F', 'F'}, {1, 2, 0}, {'L', 'R', 'R'}, {1, 1, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'R'}, {0, 2, 1}, {'L', 'L', 'R'}, {2, 1, 1}});
    pats.push_back(Pattern{3, {'F', 'F', 'L'}, {2, 2, 1}, {'L', 'R', 'L'}, {2, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'L', 'F'}, {1, 0, 1}, {'R', 'L', 'L'}, {2, 2, 1}});
    pats.push_back(Pattern{3, {'F', 'L', 'L'}, {2, 2, 0}, {'R', 'R', 'L'}, {0, 2, 0}});
    pats.push_back(Pattern{3, {'L', 'L', 'F'}, {0, 2, 1}, {'R', 'L', 'R'}, {1, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'L', 'F'}, {1, 2, 1}, {'L', 'L', 'R'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'L', 'L', 'F'}, {2, 0, 0}, {'L', 'R', 'R'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'L', 'F', 'L'}, {1, 2, 1}, {'R', 'R', 'L'}, {0, 1, 1}});
    pats.push_back(Pattern{3, {'F', 'F', 'R'}, {2, 2, 1}, {'L', 'L', 'R'}, {2, 0, 1}});
    pats.push_back(Pattern{3, {'F', 'R', 'F'}, {0, 2, 1}, {'R', 'R', 'L'}, {1, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'L', 'L'}, {1, 0, 2}, {'R', 'L', 'R'}, {2, 0, 0}});
    pats.push_back(Pattern{3, {'F', 'R', 'R'}, {2, 2, 0}, {'L', 'L', 'R'}, {0, 2, 0}});
    pats.push_back(Pattern{3, {'L', 'F', 'F'}, {2, 0, 0}, {'L', 'L', 'R'}, {1, 0, 2}});
    pats.push_back(Pattern{3, {'F', 'F', 'R'}, {1, 2, 1}, {'R', 'L', 'R'}, {2, 1, 1}});
    pats.push_back(Pattern{3, {'R', 'R', 'F'}, {2, 2, 0}, {'R', 'L', 'L'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'F'}, {1, 0, 1}, {'L', 'R', 'L'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'L', 'F', 'F'}, {1, 0, 0}, {'L', 'R', 'L'}, {1, 1, 0}});
    pats.push_back(Pattern{3, {'R', 'R', 'F'}, {1, 2, 1}, {'L', 'R', 'L'}, {1, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'F'}, {1, 0, 1}, {'L', 'R', 'R'}, {0, 2, 1}});
    pats.push_back(Pattern{3, {'L', 'F', 'L'}, {1, 0, 0}, {'L', 'R', 'R'}, {1, 1, 0}});
    pats.push_back(Pattern{3, {'R', 'F', 'F'}, {2, 2, 0}, {'R', 'L', 'L'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'F'}, {2, 2, 0}, {'R', 'R', 'L'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'R'}, {1, 0, 2}, {'R', 'L', 'L'}, {1, 2, 1}});
    pats.push_back(Pattern{2, {'F', 'L', 'R'}, {1, 0, 0}, {'R', 'L', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'F', 'F', 'R'}, {2, 2, 0}, {'L', 'R', 'R'}, {1, 2, 1}});
    pats.push_back(Pattern{2, {'F', 'R', 'R'}, {1, 0, 0}, {'L', 'R', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'F', 'F'}, {1, 0, 2}, {'R', 'L', 'R'}, {1, 1, 2}});
    pats.push_back(Pattern{3, {'F', 'F', 'L'}, {2, 2, 0}, {'R', 'L', 'L'}, {1, 2, 1}});
    pats.push_back(Pattern{3, {'F', 'R', 'R'}, {1, 0, 2}, {'L', 'R', 'L'}, {2, 0, 0}});
    pats.push_back(Pattern{2, {'R', 'F', 'R'}, {1, 0, 0}, {'R', 'L', 'R'}, {1, 1, 0}});
    pats.push_back(Pattern{2, {'L', 'F', 'R'}, {1, 0, 0}, {'L', 'R', 'R'}, {1, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'F', 'F'}, {1, 0, 0}, {'L', 'R', 'L'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'F', 'F'}, {1, 2, 1}, {'L', 'L', 'R'}, {0, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'F', 'F'}, {2, 2, 0}, {'R', 'L', 'L'}, {1, 1, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'F'}, {1, 2, 2}, {'L', 'L', 'L'}, {1, 0, 0}});
    pats.push_back(Pattern{3, {'F', 'F', 'R'}, {0, 2, 0}, {'L', 'L', 'L'}, {1, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'F'}, {2, 0, 2}, {'L', 'L', 'L'}, {1, 0, 1}});
    pats.push_back(Pattern{3, {'F', 'L', 'F'}, {1, 2, 2}, {'R', 'R', 'R'}, {1, 0, 0}});
    pats.push_back(Pattern{3, {'L', 'F', 'F'}, {1, 1, 0}, {'R', 'R', 'R'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'F', 'L'}, {0, 2, 0}, {'R', 'R', 'R'}, {1, 2, 1}});
    pats.push_back(Pattern{3, {'F', 'F', 'F'}, {1, 2, 0}, {'R', 'R', 'L'}, {1, 0, 1}});
    pats.push_back(Pattern{3, {'F', 'F', 'F'}, {1, 2, 0}, {'L', 'R', 'R'}, {2, 2, 1}});
    pats.push_back(Pattern{3, {'F', 'F', 'F'}, {1, 2, 0}, {'R', 'L', 'R'}, {2, 0, 0}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {2, 0, 1}, {'L', 'L', 'L'}, {0, 2, 1}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {2, 0, 1}, {'R', 'R', 'R'}, {0, 2, 1}});
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {1, 2, 0}, {'L', 'L', 'L'}, {0, 0, 1}});
    pats.push_back(Pattern{3, {'L', 'F', 'R'}, {2, 0, 1}, {'R', 'R', 'R'}, {1, 0, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {2, 0, 1}, {'L', 'L', 'L'}, {1, 0, 2}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {1, 2, 0}, {'R', 'R', 'R'}, {2, 0, 2}});
    pats.push_back(Pattern{3, {'L', 'R', 'F'}, {1, 2, 0}, {'R', 'R', 'R'}, {2, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'L', 'R'}, {2, 0, 1}, {'L', 'L', 'L'}, {1, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {2, 0, 1}, {'R', 'R', 'R'}, {2, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'R', 'L'}, {1, 2, 0}, {'L', 'L', 'L'}, {1, 0, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'L'}, {1, 2, 0}, {'R', 'R', 'R'}, {0, 2, 1}});
    pats.push_back(Pattern{3, {'R', 'L', 'F'}, {1, 2, 0}, {'L', 'L', 'L'}, {2, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'L', 'F'}, {0, 0, 1}, {'L', 'L', 'L'}, {2, 0, 1}});
    pats.push_back(Pattern{3, {'F', 'F', 'L'}, {0, 2, 0}, {'L', 'L', 'L'}, {1, 2, 0}});
    pats.push_back(Pattern{3, {'L', 'F', 'F'}, {1, 1, 0}, {'L', 'L', 'L'}, {1, 2, 0}});
    pats.push_back(Pattern{3, {'F', 'R', 'F'}, {1, 2, 2}, {'R', 'R', 'R'}, {1, 2, 0}});
    pats.push_back(Pattern{3, {'R', 'F', 'F'}, {1, 1, 0}, {'R', 'R', 'R'}, {1, 2, 0}});
    pats.push_back(Pattern{3, {'F', 'F', 'R'}, {2, 1, 1}, {'R', 'R', 'R'}, {2, 0, 1}});
    pats.push_back(Pattern{3, {'R', 'R', 'F'}, {2, 2, 0}, {'L', 'L', 'L'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'F', 'R', 'R'}, {2, 2, 0}, {'L', 'L', 'L'}, {0, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'F', 'R'}, {1, 0, 2}, {'L', 'L', 'L'}, {0, 1, 2}});
    pats.push_back(Pattern{2, {'R', 'F', 'R'}, {1, 0, 0}, {'L', 'L', 'R'}, {0, 1, 0}});
    pats.push_back(Pattern{2, {'F', 'R', 'R'}, {1, 0, 0}, {'L', 'L', 'R'}, {0, 1, 0}});
    pats.push_back(Pattern{2, {'F', 'F', 'R'}, {0, 0, 0}, {'R', 'L', 'R'}, {1, 1, 0}});
    pats.push_back(Pattern{2, {'F', 'F', 'R'}, {1, 1, 0}, {'L', 'R', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{2, {'F', 'R', 'R'}, {0, 0, 0}, {'R', 'R', 'R'}, {1, 0, 0}});
    pats.push_back(Pattern{2, {'F', 'L', 'R'}, {0, 0, 0}, {'L', 'L', 'R'}, {1, 0, 0}});
    pats.push_back(Pattern{2, {'R', 'F', 'R'}, {1, 1, 0}, {'R', 'R', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{2, {'L', 'F', 'R'}, {1, 1, 0}, {'L', 'L', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'F', 'F', 'F'}, {0, 2, 1}, {'L', 'L', 'L'}, {2, 2, 0}});
    pats.push_back(Pattern{1, {'F', 'R', 'R'}, {0, 0, 0}, {'L', 'R', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{2, {'F', 'F', 'R'}, {0, 0, 0}, {'L', 'L', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'L', 'L', 'F'}, {2, 2, 0}, {'R', 'R', 'R'}, {0, 0, 2}});
    pats.push_back(Pattern{3, {'L', 'F', 'L'}, {2, 2, 1}, {'R', 'R', 'R'}, {2, 0, 1}});
    pats.push_back(Pattern{3, {'F', 'L', 'L'}, {1, 0, 2}, {'R', 'R', 'R'}, {2, 2, 0}});
    pats.push_back(Pattern{2, {'F', 'L', 'R'}, {1, 0, 0}, {'R', 'R', 'R'}, {0, 1, 0}});
    pats.push_back(Pattern{2, {'L', 'F', 'R'}, {1, 0, 0}, {'R', 'R', 'R'}, {1, 1, 0}});
    pats.push_back(Pattern{3, {'F', 'F', 'F'}, {1, 1, 2}, {'R', 'R', 'R'}, {1, 1, 2}});
    pats.push_back(Pattern{1, {'F', 'R', 'R'}, {0, 0, 0}, {'R', 'R', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{2, {'F', 'F', 'R'}, {0, 0, 0}, {'R', 'R', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'R'}, {1, 2, 2}, {'R', 'R', 'L'}, {2, 0, 0}});
    pats.push_back(Pattern{3, {'L', 'L', 'L'}, {2, 2, 2}, {'L', 'L', 'L'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'L', 'L'}, {1, 2, 2}, {'R', 'L', 'L'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'L', 'L'}, {1, 2, 2}, {'R', 'L', 'R'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'L', 'R'}, {1, 2, 2}, {'R', 'L', 'L'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'L', 'R'}, {1, 2, 2}, {'R', 'L', 'R'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'L', 'L'}, {1, 2, 2}, {'R', 'R', 'L'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'L', 'L'}, {1, 2, 2}, {'R', 'R', 'R'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'R', 'R'}, {1, 0, 0}, {'L', 'R', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'R', 'R'}, {1, 0, 0}, {'L', 'R', 'L'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'R', 'L'}, {1, 0, 0}, {'L', 'R', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'R', 'L'}, {1, 0, 0}, {'L', 'R', 'L'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'R'}, {1, 2, 2}, {'R', 'R', 'R'}, {2, 2, 2}});
    pats.push_back(Pattern{3, {'R', 'R', 'R'}, {1, 0, 0}, {'L', 'L', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'R', 'R'}, {1, 0, 0}, {'L', 'L', 'L'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'R', 'L'}, {1, 0, 0}, {'L', 'L', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'R', 'L'}, {1, 0, 0}, {'L', 'L', 'L'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'R'}, {1, 0, 0}, {'L', 'R', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'R'}, {1, 0, 0}, {'L', 'R', 'L'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'L'}, {1, 0, 0}, {'L', 'R', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'L'}, {1, 0, 0}, {'L', 'R', 'L'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'R'}, {1, 0, 0}, {'L', 'L', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'R'}, {1, 0, 0}, {'L', 'L', 'L'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'L'}, {1, 0, 0}, {'L', 'L', 'R'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'L', 'L'}, {1, 0, 0}, {'L', 'L', 'L'}, {0, 0, 0}});
    pats.push_back(Pattern{3, {'R', 'R', 'L'}, {1, 2, 2}, {'R', 'L', 'L'}, {2, 2, 2}});

    // Remove duplicate transition tables.
    unordered_map<string, int> seen;
    seen.reserve(pats.size() * 2 + 16);
    vector<Pattern> uniq;
    uniq.reserve(pats.size());
    for (const auto &p : pats) {
        string key;
        key.reserve(1 + 4 * p.m);
        key.push_back((char)('0' + p.m));
        for (int s = 0; s < p.m; s++) {
            key.push_back(p.a0[s]);
            key.push_back((char)('a' + p.b0[s]));
            key.push_back(p.a1[s]);
            key.push_back((char)('a' + p.b1[s]));
        }
        if (seen.emplace(key, 1).second) uniq.push_back(p);
    }

    return uniq;
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    int Nin, AK, AM, AW;
    if (!(cin >> Nin >> AK >> AM >> AW)) return 0;

    vector<string> v(N), h(N - 1);
    for (int i = 0; i < N; i++)
        cin >> v[i];
    for (int i = 0; i < N - 1; i++)
        cin >> h[i];

    static const int di[4] = {-1, 0, 1, 0};
    static const int dj[4] = {0, 1, 0, -1};
    static const char DIR_CH[4] = {'U', 'R', 'D', 'L'};

    bool blocked[CELLS][DIRS];
    int forward_cell[CELLS][DIRS];
    for (int i = 0; i < N; i++) {
        for (int j = 0; j < N; j++) {
            int cell = i * N + j;
            for (int d = 0; d < DIRS; d++) {
                bool w = false;
                if (d == 0) {
                    w = (i == 0) || (h[i - 1][j] == '1');
                } else if (d == 1) {
                    w = (j == N - 1) || (v[i][j] == '1');
                } else if (d == 2) {
                    w = (i == N - 1) || (h[i][j] == '1');
                } else {
                    w = (j == 0) || (v[i][j - 1] == '1');
                }
                blocked[cell][d] = w;
                if (w) {
                    forward_cell[cell][d] = cell;
                } else {
                    int ni = i + di[d];
                    int nj = j + dj[d];
                    forward_cell[cell][d] = ni * N + nj;
                }
            }
        }
    }

    vector<Pattern> patterns = build_patterns();

    vector<Candidate> cands;
    cands.reserve(40000);
    unordered_map<Mask, int, MaskHash> uniq;
    uniq.reserve(1 << 16);

    auto add_candidate = [&](Candidate &&cand) {
        if (is_zero(cand.mask)) return;
        int cov = popcount(cand.mask);
        if (cov <= cand.cost) return;

        auto it = uniq.find(cand.mask);
        if (it == uniq.end()) {
            int id = (int)cands.size();
            uniq.emplace(cand.mask, id);
            cands.push_back(std::move(cand));
            return;
        }

        int id = it->second;
        if (cand.cost < cands[id].cost) {
            cands[id] = std::move(cand);
        }
    };

    auto generate_for_pattern = [&](int pat_idx) {
        const Pattern &p = patterns[pat_idx];
        int m = p.m;
        int S = CELLS * DIRS * m;

        vector<int> nxt(S);
        for (int node = 0; node < S; node++) {
            int s = node % m;
            int t = node / m;
            int d = t % DIRS;
            int cell = t / DIRS;

            bool w = blocked[cell][d];
            char act = w ? p.a1[s] : p.a0[s];
            int ns = w ? p.b1[s] : p.b0[s];

            int nd = d;
            int ncell = cell;
            if (act == 'F') {
                ncell = forward_cell[cell][d];
            } else if (act == 'R') {
                nd = (d + 1) & 3;
            } else {
                nd = (d + 3) & 3;
            }

            nxt[node] = ((ncell * DIRS + nd) * m + ns);
        }

        vector<uint8_t> state(S, 0); // 0 unvisited, 1 visiting, 2 done
        vector<int> idx(S, -1);
        vector<int> comp(S, -1);
        vector<int> path;
        path.reserve(S);

        int cycle_count = 0;
        vector<vector<int>> cycles;
        cycles.reserve(S / 2 + 1);
        for (int st = 0; st < S; st++) {
            if (state[st] != 0) continue;

            path.clear();
            int u = st;
            while (state[u] == 0) {
                state[u] = 1;
                idx[u] = (int)path.size();
                path.push_back(u);
                u = nxt[u];
            }

            if (state[u] == 1) {
                int from = idx[u];
                int cid = cycle_count++;
                cycles.emplace_back();
                cycles.back().reserve((int)path.size() - from);
                for (int t = from; t < (int)path.size(); t++) {
                    int vtx = path[t];
                    comp[vtx] = cid;
                    state[vtx] = 2;
                    cycles.back().push_back(vtx);
                }
            }

            for (int t = (int)path.size() - 1; t >= 0; t--) {
                int vtx = path[t];
                if (state[vtx] == 2) continue;
                comp[vtx] = comp[nxt[vtx]];
                state[vtx] = 2;
            }

            for (int vtx : path)
                idx[vtx] = -1;
        }

        vector<Mask> cycle_masks(cycle_count);
        for (int cid = 0; cid < cycle_count; cid++) {
            for (int node : cycles[cid]) {
                int cell = node / (DIRS * m);
                set_bit(cycle_masks[cid], cell);
            }
        }

        vector<vector<uint16_t>> cycle_cells(cycle_count);
        for (int cid = 0; cid < cycle_count; cid++) {
            for_each_cell(cycle_masks[cid], [&](int cell) {
                cycle_cells[cid].push_back((uint16_t)cell);
            });
        }

        for (int cell = 0; cell < CELLS; cell++) {
            int i = cell / N;
            int j = cell % N;
            for (int d = 0; d < DIRS; d++) {
                int st_node = ((cell * DIRS + d) * m + 0);
                int cid = comp[st_node];

                Candidate cand;
                cand.i = i;
                cand.j = j;
                cand.d = d;
                cand.pat_idx = pat_idx;
                cand.cost = m;
                cand.mask = cycle_masks[cid];
                cand.cells = cycle_cells[cid];
                add_candidate(std::move(cand));
            }
        }
    };

    for (int pat_idx = 0; pat_idx < (int)patterns.size(); pat_idx++) {
        generate_for_pattern(pat_idx);
    }

    const int C = (int)cands.size();
    vector<char> selected(C, 0);
    vector<int> cover_cnt(CELLS, 0);
    int uncovered = CELLS;
    int cost_sum = 0;
    Mask uncovered_mask{};
    Mask single_mask{};
    for (int cell = 0; cell < CELLS; cell++) set_bit(uncovered_mask, cell);
    vector<int> selected_ids;
    vector<int> unselected_ids(C);
    vector<int> pos_selected(C, -1);
    vector<int> pos_unselected(C, -1);
    for (int id = 0; id < C; id++) {
        unselected_ids[id] = id;
        pos_unselected[id] = id;
    }

    auto move_to_selected = [&](int id) {
        int pu = pos_unselected[id];
        if (pu != -1) {
            int tail = unselected_ids.back();
            unselected_ids[pu] = tail;
            pos_unselected[tail] = pu;
            unselected_ids.pop_back();
            pos_unselected[id] = -1;
        }
        if (pos_selected[id] == -1) {
            pos_selected[id] = (int)selected_ids.size();
            selected_ids.push_back(id);
        }
    };

    auto move_to_unselected = [&](int id) {
        int ps = pos_selected[id];
        if (ps != -1) {
            int tail = selected_ids.back();
            selected_ids[ps] = tail;
            pos_selected[tail] = ps;
            selected_ids.pop_back();
            pos_selected[id] = -1;
        }
        if (pos_unselected[id] == -1) {
            pos_unselected[id] = (int)unselected_ids.size();
            unselected_ids.push_back(id);
        }
    };

    auto add_selected = [&](int id) {
        if (selected[id]) return;
        selected[id] = 1;
        move_to_selected(id);
        cost_sum += cands[id].cost;
        for (uint16_t cell : cands[id].cells) {
            int cnt = cover_cnt[cell];
            if (cnt == 0) {
                uncovered--;
                clear_bit(uncovered_mask, cell);
                set_bit(single_mask, cell);
            } else if (cnt == 1) {
                clear_bit(single_mask, cell);
            }
            cover_cnt[cell] = cnt + 1;
        }
    };

    auto remove_selected = [&](int id) {
        if (!selected[id]) return;
        selected[id] = 0;
        move_to_unselected(id);
        cost_sum -= cands[id].cost;
        for (uint16_t cell : cands[id].cells) {
            int cnt = cover_cnt[cell];
            if (cnt == 1) {
                uncovered++;
                set_bit(uncovered_mask, cell);
                clear_bit(single_mask, cell);
            } else if (cnt == 2) {
                set_bit(single_mask, cell);
            }
            cover_cnt[cell] = cnt - 1;
        }
    };

    auto objective = [&]() -> int {
        return cost_sum + uncovered;
    };

    // Greedy initialization: add candidate if it strictly improves objective.
    while (true) {
        int best = -1;
        int best_delta = 0;
        int best_gain = 0;

        for (int id = 0; id < C; id++) {
            int gain = popcount_and(cands[id].mask, uncovered_mask);
            int delta = cands[id].cost - gain;
            if (best == -1 || delta < best_delta || (delta == best_delta && gain > best_gain)) {
                best = id;
                best_delta = delta;
                best_gain = gain;
            }
        }

        if (best == -1 || best_delta >= 0) break;
        add_selected(best);
    }

    int best_obj = objective();
    vector<char> best_selected = selected;

    // Simulated annealing with toggle + occasional swap moves.
    if (C > 0) {
        const auto start_time = chrono::steady_clock::now();
        const double time_limit = 1.60;
        const double T0 = 2.5;
        const double T1 = 0.02;

        uint64_t seed = (uint64_t)chrono::high_resolution_clock::now().time_since_epoch().count();
        seed ^= (uint64_t)Nin * 1000003ULL + (uint64_t)AK * 10007ULL + (uint64_t)AM * 257ULL + (uint64_t)AW;
        XorShift64 rng(seed);

        double temp = T0;
        int iter = 0;

        while (true) {
            if ((iter & 255) == 0) {
                double elapsed = chrono::duration<double>(chrono::steady_clock::now() - start_time).count();
                if (elapsed >= time_limit) break;
                double p = elapsed / time_limit;
                temp = T0 * pow(T1 / T0, p);
            }
            iter++;

            // Swap move: selected -> unselected.
            if (!selected_ids.empty() && !unselected_ids.empty() && ((iter & 1) == 0)) {
                int a = selected_ids[rng.next_int((int)selected_ids.size())];
                int b = unselected_ids[rng.next_int((int)unselected_ids.size())];

                int lost = popcount_and(cands[a].mask, single_mask);
                int gain = 0;
                for (uint16_t cell : cands[b].cells) {
                    int cnt = cover_cnt[cell];
                    if (cnt == 0 || (cnt == 1 && test_bit(cands[a].mask, cell))) gain++;
                }
                int delta = (-cands[a].cost + lost) + (cands[b].cost - gain);

                bool accept = false;
                if (delta <= 0) {
                    accept = true;
                } else {
                    double prob = exp(-double(delta) / temp);
                    if (rng.next_double() < prob) accept = true;
                }

                if (accept) {
                    remove_selected(a);
                    add_selected(b);
                    int obj = objective();
                    if (obj < best_obj) {
                        best_obj = obj;
                        best_selected = selected;
                    }
                }
                continue;
            }

            // Toggle move.
            bool do_remove = false;
            if (unselected_ids.empty()) do_remove = true;
            else if (selected_ids.empty()) do_remove = false;
            else if (uncovered == 0) do_remove = (rng.next_int(100) < 58);
            else do_remove = (rng.next_int(100) < 22);

            int id = -1;
            int delta = 0;
            if (do_remove) {
                int samples = min<int>(6, selected_ids.size());
                int best_id = selected_ids[rng.next_int((int)selected_ids.size())];
                int best_delta = numeric_limits<int>::max();
                for (int s = 0; s < samples; s++) {
                    int cand_id = selected_ids[rng.next_int((int)selected_ids.size())];
                    int lost = popcount_and(cands[cand_id].mask, single_mask);
                    int cand_delta = -cands[cand_id].cost + lost;
                    if (cand_delta < best_delta) {
                        best_delta = cand_delta;
                        best_id = cand_id;
                    }
                }
                id = best_id;
                delta = best_delta;
            } else {
                int samples = min<int>(8, unselected_ids.size());
                int best_id = unselected_ids[rng.next_int((int)unselected_ids.size())];
                int best_delta = numeric_limits<int>::max();
                for (int s = 0; s < samples; s++) {
                    int cand_id = unselected_ids[rng.next_int((int)unselected_ids.size())];
                    int gain = popcount_and(cands[cand_id].mask, uncovered_mask);
                    int cand_delta = cands[cand_id].cost - gain;
                    if (cand_delta < best_delta) {
                        best_delta = cand_delta;
                        best_id = cand_id;
                    }
                }
                id = best_id;
                delta = best_delta;
            }

            bool accept = false;
            if (delta <= 0) {
                accept = true;
            } else {
                double prob = exp(-double(delta) / temp);
                if (rng.next_double() < prob) accept = true;
            }
            if (!accept) continue;

            if (do_remove) remove_selected(id);
            else add_selected(id);

            int obj = objective();
            if (obj < best_obj) {
                best_obj = obj;
                best_selected = selected;
            }
        }
    }

    // Restore best solution and perform deterministic local prune.
    vector<char> restored = best_selected;
    fill(selected.begin(), selected.end(), 0);
    fill(cover_cnt.begin(), cover_cnt.end(), 0);
    uncovered = CELLS;
    cost_sum = 0;
    uncovered_mask = Mask{};
    single_mask = Mask{};
    for (int cell = 0; cell < CELLS; cell++) set_bit(uncovered_mask, cell);
    selected_ids.clear();
    unselected_ids.clear();
    unselected_ids.reserve(C);
    fill(pos_selected.begin(), pos_selected.end(), -1);
    fill(pos_unselected.begin(), pos_unselected.end(), -1);
    for (int id = 0; id < C; id++) {
        pos_unselected[id] = (int)unselected_ids.size();
        unselected_ids.push_back(id);
    }
    for (int id = 0; id < C; id++) {
        if (restored[id]) add_selected(id);
    }

    bool improved = true;
    while (improved) {
        improved = false;
        for (int id = 0; id < C; id++) {
            if (!selected[id]) continue;
            int lost = popcount_and(cands[id].mask, single_mask);
            int delta = -cands[id].cost + lost;
            if (delta < 0) {
                remove_selected(id);
                improved = true;
                break;
            }
        }
    }

    // Build output robots.
    struct RobotOut {
        int m;
        int i, j, d;
        array<char, MAXM> a0;
        array<uint8_t, MAXM> b0;
        array<char, MAXM> a1;
        array<uint8_t, MAXM> b1;
    };

    vector<RobotOut> robots;
    robots.reserve(CELLS);

    for (int id = 0; id < C; id++) {
        if (!selected[id]) continue;
        const Candidate &c = cands[id];
        const Pattern &p = patterns[c.pat_idx];

        RobotOut rb;
        rb.m = p.m;
        rb.i = c.i;
        rb.j = c.j;
        rb.d = c.d;
        rb.a0 = p.a0;
        rb.b0 = p.b0;
        rb.a1 = p.a1;
        rb.b1 = p.b1;
        robots.push_back(rb);
    }

    for (int cell = 0; cell < CELLS; cell++) {
        if (cover_cnt[cell] > 0) continue;
        RobotOut rb;
        rb.m = 1;
        rb.i = cell / N;
        rb.j = cell % N;
        rb.d = 0;
        rb.a0 = {'R', 'R', 'R'};
        rb.b0 = {0, 0, 0};
        rb.a1 = {'R', 'R', 'R'};
        rb.b1 = {0, 0, 0};
        robots.push_back(rb);
    }

    // Output
    cout << robots.size() << '\n';
    for (const auto &rb : robots) {
        cout << rb.m << ' ' << rb.i << ' ' << rb.j << ' ' << DIR_CH[rb.d] << '\n';
        for (int s = 0; s < rb.m; s++) {
            cout << rb.a0[s] << ' ' << (int)rb.b0[s] << ' ' << rb.a1[s] << ' ' << (int)rb.b1[s] << '\n';
        }
    }

    // A problem: no additional walls.
    for (int i = 0; i < N; i++)
        cout << string(N - 1, '0') << '\n';
    for (int i = 0; i < N - 1; i++)
        cout << string(N, '0') << '\n';

    return 0;
}
