[general]
version = "0.3.1"

[problem]
problem_name = "masters2026-qual"
objective = "Max"
score_regex = '(?m)^\s*Score\s*=\s*(?P<score>\d+)\s*$'

[test]
start_seed = 0
end_seed = 100
threads = 0
out_dir = "./pahcer"

# ==============================
#         COMPILE STEPS
# ==============================

# Compile the user's program
[[test.compile_steps]]
program = "g++-14"
args = ["-std=c++20", "-O2", "main.cpp"]

# On macOS, there’s a possibility of SIGKILL or other issues occurring, 
# so it’s better to build the visualizer in advance
# rather than running it with cargo run every time.

# Compile the visualizer and generator
[[test.compile_steps]]
program = "cargo"
args = ["build", "--release", "--bin", "score", "--bin", "gen"]
current_dir = "./tools"

# Generate input files (tools/inA/0000.txt .. 0100.txt)
[[test.compile_steps]]
program = "./target/release/gen"
args = ["seeds.txt", "A", "--dir", "inA"]
current_dir = "./tools"

# Remove the old tester
[[test.compile_steps]]
program = "rm"
args = ["-f", "./vis"]

# Move the tester to the current directory
[[test.compile_steps]]
program = "mv"
args = ["./tools/target/release/score", "./vis"]

# ==============================
#           TEST STEPS
# ==============================

# Run the user's program
[[test.test_steps]]
program = "./a.out"
args = []
stdin = "./tools/inA/{SEED04}.txt"
stdout = "./tools/outA/{SEED04}.txt"
stderr = "./tools/err/{SEED04}.txt"
measure_time = true

# Run the visualizer to calculate the score
[[test.test_steps]]
program = "./vis"
args = ["./tools/inA/{SEED04}.txt", "./tools/outA/{SEED04}.txt"]
measure_time = false

